### ISSUE TITLE
Please, link your images to a base image they use on DockerHub

### ISSUE THREAD

**Issue by frol** [ViBiOh/docker-php#3]
Build Settings -> Repository Link

> Link your Automated Build to another Docker Hub repository, and when that repository is updated, it will automatically trigger a rebuild of this Automated Build.

This will make your images up-to-date with the latest updates. For example, only today Alpine has been finally released with the fix of passwordless `su` to root from any user: https://github.com/gliderlabs/docker-alpine/issues/101

P.S. Don't forget to hit "Trigger" since the links will work only starting the next linked image push.

**Comment by ViBiOh** [comment]
Got that in mind since the change of the alpine:3.3, done ;)
